### ISSUE TITLE
Incompatibility with masked reference genomes

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#49] opened 2018-11-03 17:16 UTC
**Incompatibility with masked reference genomes**

`call-macs2` fails if a masked reference (where Ns are used to indicate repetitive regions) is used to build a custom genome reference database. 

```
run_shell_cmd: PID=70151, CMD=bedtools intersect -a ${SAMPLE}.trim.merged.nodup.tn5.tagAlign.tmp1 -b ${SAMPLE}.trim.merged.nodup.tn5.pval0.01.300K.bfilt.narrowPeak.tmp2 -wa -u | wc -l

Traceback (most recent call last):
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 210, in <module>
    main()
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 200, in main
    frip_qc = frip( args.ta, bfilt_npeak, args.out_dir)
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_frip.py", line 54, in frip
    write_txt(frip_qc, str(float(val1)/float(val2)))
ValueError: could not convert string to float: ***** WARNING: File rat_liver7_S12_L001_R1_001.trim.merged.nodup.tn5.tagAlign.tmp1 has inconsistent naming convention for record:
AABR07024382.1	100568	100639	N	1000	+
```

If it would be impractical to include compatibility with masked references, it would be helpful to specify that the pipeline is incompatible with masked references in the documentation. I understand that this is the function of the blacklist input, but blacklisted regions can be more difficult to define for less popular model organisms.

**Comment by nicolerg** [comment] 2018-11-03 17:55
Yes, the problem occurs during FRiP calculation after macs2 calls peaks, but that command is called within the `call-macs2` module, or at least the error was documented within the `call-macs2` subdirectory of the output folder. It looks like an issue with the masking to me because every sample I ran generated this error where the problematic record reported in the error had an "N" in the "sequence" field.

**Comment by akundaje** [comment] 2018-11-03 18:29
The N you see in the tagAlign files is not a masking issue. We explicitly
generate tagAlign files with N in the sequence field of every read to save
disk space (we don't need the read sequences post alignment). So the Ns you
are seeing are by design. It doesn't have anything to do with a masked
reference. I actually think the issue might actually be the chromosome
names or a reference with very small unplaced contigs thats creating some
edge case. We'll look into it.

**Comment by nicolerg** [comment] 2018-11-03 18:56
Thank you for the clarification. It could definitely be an issue with the reference. I am using rat (rn6).

**Comment by akundaje** [comment] 2018-11-03 19:01
Thanks. When you get a chance could you try running the pipeline using only
the complete assembled chromosomes to see if you get the same error. That
would help us narrow the possibilities.

Anshul

**Comment by nicolerg** [comment] 2018-11-03 19:05
Yes, I have been able to run the pipeline with the UCSC soft-masked version of the rat genome (including contigs). This run was with a hard-masked version from Ensembl to see what the results looked like in comparison since there are some questions about the quality of the rat assembly, but it is not entirely necessary to use the hard-masked version. In fact it may be too limiting.

**Comment by akundaje** [comment] 2018-11-03 19:13
Interesting. This is a bug/unintended behavior so we'd like to get to the
bottom of it. I'll ask @jinlee to get in touch with you so we can get to
the bottom of it and fix the issue.

**Comment by leepc12** [comment] 2018-11-07 18:10
This is actually a duplicate issue of #48 and will be fixed in the next release.

**Comment by leepc12** [comment] 2018-11-20 02:08
Fixed in branch `PIP-418_v1.1.2`. This will be merged into master soon.

**Closed** 2019-09-09 21:29 UTC
