### ISSUE TITLE
Build Genome Database stuck at Entering Ebwt loop

### ISSUE THREAD

**Issue by 5im1z** [ENCODE-DCC/atac-seq-pipeline#298] opened 2020-11-17 16:47 UTC
Hi,

## **Describe the bug**
I'm running build_genome_data.sh with >30G memory to build a tsv file, but it always gets stuck at "entering ebwt loop"

## **OS/Platform**
- OS/Platform: Linux cluster with Centos 7
- Conda version: v4.9.2
- Pipeline version: v1.9.1
- Caper version: v1.1.0

## Output from bash scripts/build_genome_data.sh [GENOME] [DESTINATION_DIR]
...
Reading reference sizes

  Time reading reference sizes: 00:00:11

Calculating joined length

Writing header

Reserving space for joined string

Joining reference sequences

  Time to join reference sequences: 00:00:09

bmax according to bmaxDivN setting: 233368027

Using parameters --bmax 175026021 --dcv 1024

  Doing ahead-of-time memory usage test

  Passed!  Constructing with these parameters: --bmax 175026021 --dcv 1024

Constructing suffix-array element generator

Building DifferenceCoverSample

  Building sPrime

  Building sPrimeOrder

  V-Sorting samples

  V-Sorting samples time: 00:00:31

  Allocating rank array

  Ranking v-sort output

  Ranking v-sort output time: 00:00:08

  Invoking Larsson-Sadakane on ranks

  Invoking Larsson-Sadakane on ranks time: 00:00:18

  Sanity-checking and returning

Building samples

Reserving space for 22 sample suffixes

Generating random suffixes

QSorting 22 sample offsets, eliminating duplicates

QSorting sample offsets, eliminating duplicates time: 00:00:00

Multikey QSorting 22 samples

  (Using difference cover)

  Multikey QSorting samples time: 00:00:00

Calculating bucket sizes

Splitting and merging

  Splitting and merging time: 00:00:00

Split 3, merged 9; iterating...

Splitting and merging

  Splitting and merging time: 00:00:00

Split 1, merged 3; iterating...

Splitting and merging

  Splitting and merging time: 00:00:00

Split 1, merged 1; iterating...

Splitting and merging

  Splitting and merging time: 00:00:00

Avg bucket size: 1.33353e+08 (target: 175026020)

Converting suffix-array elements to index image

Allocating ftab, absorbFtab

Entering Ebwt loop

**Comment by leepc12** [comment] 2020-11-18 23:51
I think it's just taking long? For me it took 2-3 hours with 4 cpus on my cluster.

**Comment by 5im1z** [comment] 2020-11-19 00:48
Sorry for being unclear in the post, but it actually had been stuck at this step for >3 days so I'm wondering what else might the issue be. Thanks!

**Comment by leepc12** [comment] 2021-01-07 20:21
I can't help you much about this issue since it looks like bowtie2's issue.

I am closing it but please re-open this if you need further assistance.

**Closed by leepc12** 2021-01-07 20:21 UTC

**Comment by imk1** [comment] 2024-09-24 21:31
I think that the problem is that the version of bowtie2 in the pipeline sometimes causes this error.  I had this problem and upgraded bowtie2 to version 2.5.4, and that solved it for me.
